name: Release
run-name: Release ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Version number to release (e.g., "v1.2.3")
      pre-release:
        required: false
        type: boolean
        description: Is this a pre-release (e.g., alpha, beta, rc)?
        default: false

env:
  GH_TOKEN: ${{ github.token }}
  build_path: target/release
  executable: webserver
  executable_display_label_prefix: webserver-${{ inputs.version }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Print Rust Version
        run: rustup --version
        continue-on-error: true

      - name: Build
        run: cargo build --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.executable }}-${{ matrix.os }}
          path: |
            ${{ env.build_path }}/${{ env.executable}}
            ${{ env.build_path }}/${{ env.executable}}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.build_path }}

        # This step is needed to prevent files having conflicting names when creating the release
      - name: Rename Files
        run: |
          mv ${{ env.build_path }}/${{ env.executable }}-ubuntu-latest/${{ env.executable}} \
            ${{ env.build_path }}/${{ env.executable }}-ubuntu-latest/${{ env.executable}}-${{ inputs.version }}-linux-x64
          mv ${{ env.build_path }}/${{ env.executable }}-ubuntu-24.04-arm/${{ env.executable}} \
            ${{ env.build_path }}/${{ env.executable }}-ubuntu-24.04-arm/${{ env.executable}}-${{ inputs.version }}-linux-arm64
          mv ${{ env.build_path }}/${{ env.executable }}-windows-latest/${{ env.executable}}.exe \
            ${{ env.build_path }}/${{ env.executable}}-windows-latest/${{ env.executable}}-${{ inputs.version }}-windows-x64.exe

      - name: Prerelease Option
        id: prerelease
        run: |
          if [ "${{ inputs.pre-release }}" == "true" ]; then
            echo "prerelease=--prerelease" >> $GITHUB_OUTPUT
            echo "latest=--latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        run: |
          gh release create ${{ inputs.version }} --draft --generate-notes --target "${{ github.ref_name }}" ${{ steps.prerelease.outputs.prerelease }} ${{ steps.prerelease.outputs.latest }} \
            ${{ env.build_path }}/${{ env.executable }}-ubuntu-latest/${{ env.executable}}-${{ inputs.version }}-linux-x64 \
            ${{ env.build_path }}/${{ env.executable }}-ubuntu-24.04-arm/${{ env.executable}}-${{ inputs.version }}-linux-arm64 \
            ${{ env.build_path }}/${{ env.executable}}-windows-latest/${{ env.executable}}-${{ inputs.version }}-windows-x64.exe \
            LICENSE.txt